<?php
/**
 * Created by PhpStorm.
 * User: ztwl
 * Date: 2018/11/15
 * Time: 上午9:33
 */

namespace app\admin\controller;


use think\Session;
use think\Request;

class Index extends Common
{
    public $id;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->id = Session::get('user_id');
    }

    public function index()
    {
        //dd(1);
        return view('index');
    }

    public function more()
    {
        return view('more');
    }

    //重置密码

    public function resetpwd()
    {
        if(Request::instance()->isPost()){

        }else{
//            $username = db(self::$table_user)
//                ->where(['user_id'=>$this->id])
//                ->value('username');
            $username = 'aa';
            return view('resetpwd',[
                'username' => $username
            ]);
        }
    }
}